"""Initial schema

Revision ID: 286782a66bee
Revises: 
Create Date: 2025-11-06 10:20:57.102757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286782a66bee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_order', 'categories', ['order'], unique=False)
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('ix_categories_tenant_id', 'categories', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_username', 'users', ['tenant_id', 'username'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index('ix_sessions_api_key', 'sessions', ['api_key'], unique=True)
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_tenant_id', 'sessions', ['tenant_id'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('surveys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_surveys_owner_id', 'surveys', ['owner_id'], unique=False)
    op.create_index('ix_surveys_tenant_id', 'surveys', ['tenant_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('survey_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_category_id', 'questions', ['category_id'], unique=False)
    op.create_index('ix_questions_survey_id_order', 'questions', ['survey_id', 'order'], unique=False)
    op.create_table('survey_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('survey_id', sa.String(length=36), nullable=False),
    sa.Column('respondent_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('total_time_spent_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_survey_sessions_completed', 'survey_sessions', ['completed'], unique=False)
    op.create_index('ix_survey_sessions_respondent_id', 'survey_sessions', ['respondent_id'], unique=False)
    op.create_index('ix_survey_sessions_started_at', 'survey_sessions', ['started_at'], unique=False)
    op.create_index('ix_survey_sessions_submitted_at', 'survey_sessions', ['submitted_at'], unique=False)
    op.create_index('ix_survey_sessions_survey_id', 'survey_sessions', ['survey_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('survey_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('respondent_id', sa.String(length=255), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_responses_answered_at', 'responses', ['answered_at'], unique=False)
    op.create_index('ix_responses_question_id', 'responses', ['question_id'], unique=False)
    op.create_index('ix_responses_respondent_id', 'responses', ['respondent_id'], unique=False)
    op.create_index('ix_responses_session_id', 'responses', ['session_id'], unique=False)
    op.create_index('ix_responses_survey_id', 'responses', ['survey_id'], unique=False)
    op.create_table('response_histories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('old_answer', sa.Text(), nullable=False),
    sa.Column('new_answer', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_response_histories_response_id', 'response_histories', ['response_id'], unique=False)
    op.create_index('ix_response_histories_updated_at', 'response_histories', ['updated_at'], unique=False)
    op.create_index('ix_response_histories_updated_by', 'response_histories', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_response_histories_updated_by', table_name='response_histories')
    op.drop_index('ix_response_histories_updated_at', table_name='response_histories')
    op.drop_index('ix_response_histories_response_id', table_name='response_histories')
    op.drop_table('response_histories')
    op.drop_index('ix_responses_survey_id', table_name='responses')
    op.drop_index('ix_responses_session_id', table_name='responses')
    op.drop_index('ix_responses_respondent_id', table_name='responses')
    op.drop_index('ix_responses_question_id', table_name='responses')
    op.drop_index('ix_responses_answered_at', table_name='responses')
    op.drop_table('responses')
    op.drop_index('ix_survey_sessions_survey_id', table_name='survey_sessions')
    op.drop_index('ix_survey_sessions_submitted_at', table_name='survey_sessions')
    op.drop_index('ix_survey_sessions_started_at', table_name='survey_sessions')
    op.drop_index('ix_survey_sessions_respondent_id', table_name='survey_sessions')
    op.drop_index('ix_survey_sessions_completed', table_name='survey_sessions')
    op.drop_table('survey_sessions')
    op.drop_index('ix_questions_survey_id_order', table_name='questions')
    op.drop_index('ix_questions_category_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_surveys_tenant_id', table_name='surveys')
    op.drop_index('ix_surveys_owner_id', table_name='surveys')
    op.drop_table('surveys')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_tenant_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_index('ix_sessions_api_key', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_users_tenant_username', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_categories_tenant_id', table_name='categories')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_index('ix_categories_order', table_name='categories')
    op.drop_table('categories')
    op.drop_table('tenants')
    # ### end Alembic commands ###
